# @package _group_
##########################################
##########################################
# hs: add custom data here 
lbox_fact_corpus:
  _target_: dpr.data.retriever_data.JsonCtxSrc
  file: /home/hanseok/projects/ai599_ai_for_law/project/data/fact-retrieval/corpus.json
  id_prefix: 'lbox_fact:'

lbox_statute_corpus:
  _target_: dpr.data.retriever_data.JsonCtxSrc
  file: /home/hanseok/projects/ai599_ai_for_law/project/data/statute-retrieval/corpus.json
  id_prefix: 'lbox_stat:'
##########################################
##########################################

dpr_wiki:
  _target_: dpr.data.retriever_data.CsvCtxSrc
  file: data.wikipedia_split.psgs_w100
  id_prefix: 'wiki:'